# Generated by Django 4.0.5 on 2023-02-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='locals',
            new_name='location',
        ),
    ]
